### ISSUE TITLE
isNaN()

### ISSUE THREAD

**Issue by FredTheNoob** [sindresorhus/number-is-nan#10]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/isNaN

**Comment by sindresorhus** [comment]
?

**Comment by FredTheNoob** [comment]
Why not just use the in-built one? xd

**Comment by sindresorhus** [comment]
Because it's not the same thing. `Number.isNaN` and `isNaN` are slightly different.
