### ISSUE TITLE
Bad result with 'NaN'

### ISSUE THREAD

**Issue by btamas** [sindresorhus/number-is-nan#2]
I tried your module, but it gives wrong result with parameter 'NaN'.

Number.isNaN('NaN') //true
yourFunction('NaN') //false

BTW, I like your module >:)

**Comment by SamVerschueren** [comment]
How did you get `Number.isNaN('NaN');` where `NaN` is a string to return `true`? It returns false for me to be honest.

This module is also a ponyfill which returns `Number.isNaN` if it exists https://github.com/sindresorhus/number-is-nan/blob/master/index.js#L2.

**Comment by btamas** [comment]
It was my bad. I used isNaN and not Number.isNaN. Thanks the answer.
